# .github/workflows/tests.yml
name: Tests (JUnit XML)
on:
  push:
  pull_request:
permissions:
  contents: read
  checks: write         # <-- required for creating check runs
  pull-requests: write  # <-- allows PR comments/summary updates
jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests (JUnit XML)
        run: |
          mkdir -p reports
          pytest --junitxml=reports/junit.xml
      - name: Publish JUnit results
        if: always()
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: reports/junit.xml
      - name: Upload JUnit XML artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-xml
          path: reports/junit.xml






